name: learn-github-actions

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: yarn
          run: yarn cypress run
          browser: chrome

